# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d2f517a924d12d07841ec8e6ffa605c"
name = "neat-bundle-builder"
handle = "neat-bundle-builder"
application_url = "https://lesser-others-frog-changelog.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-24926068.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_content,write_products"

[auth]
redirect_urls = [
  "https://lesser-others-frog-changelog.trycloudflare.com/auth/callback",
  "https://lesser-others-frog-changelog.trycloudflare.com/auth/shopify/callback",
  "https://lesser-others-frog-changelog.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
