# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d1990e2dad8ca94c1c3512690d18cd1"
name = "Neat Bundles - dev"
handle = "neat-bundles-dev"
application_url = "https://intermediate-races-firmware-antonio.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-24926068.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_content,write_online_store_navigation,write_products,write_publications"

[auth]
redirect_urls = [
  "https://intermediate-races-firmware-antonio.trycloudflare.com/auth/callback",
  "https://intermediate-races-firmware-antonio.trycloudflare.com/auth/shopify/callback",
  "https://intermediate-races-firmware-antonio.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[app_proxy]
url = "https://intermediate-races-firmware-antonio.trycloudflare.com"
subpath = "nb"
prefix = "apps"

